image: rabits/qt:5.10-desktop
pipelines:
  default:
      - step:
          script:
            - cat /etc/*-release
            - uname -a
            - grep -i processor /proc/cpuinfo | wc -l
            - gcc --version
            - mkdir build
            - cd build
            - qmake --version
            - qmake ../PearlLib/PearlLib.pro
            - make -j$(nproc)
            - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"PearlLib"
            - PearlLibTest/tst_pearllib_network
