image: dismine/docker-valentina
pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    develop:
      - step:
          script:
            - cat /etc/*-release
            - uname -a
            - grep -i processor /proc/cpuinfo | wc -l
            - gcc --version
            - mkdir build
            - cd build
            - qmake --version
            - qmake ../PearlLib.pro
            - make -j$(nproc)
            - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"PearlLib"
