image: gcc:latest
pipelines:
  branches:
    master:
      - step:
          script:
            - cat /etc/*-release
            - uname -a
            - grep -i processor /proc/cpuinfo | wc -l
            - apt-get update
            - apt-get install -y cmake
            - apt-get install -y gperf
            - gcc --version
            - cmake --version
            - git submodule update --init
            - mkdir build
            - cd build
            - cmake ..
            - make
            - pearl-test
