image: clearlinux:latest
pipelines:
  branches:
    master:
      - step:
          script:
            - uname -a
            - grep -i processor /proc/cpuinfo | wc -l
            - swupd bundle-add c-basic git
            - gcc --version
            - cmake --version
            - git submodule update --init
            - mkdir build
            - cd build
            - cmake ..
            - make
            - ./pearl-test
